CREATE TABLE [norman_ruiz_coderhouse].[asteroides](
	[links] VARCHAR(MAX) NULL,
	[id] INTEGER NOT NULL PRIMARY KEY,
	[neo_reference_id] INTEGER NOT NULL,
	[name] VARCHAR(50) NOT NULL,
	[nasa_jpl_url] VARCHAR(max) NOT NULL,
	[absolute_magnitude_h] DOUBLE PRECISION NOT NULL,
	[estimated_diameter_kilometers_min] DOUBLE PRECISION NULL,
	[estimated_diameter_kilometers_max] DOUBLE PRECISION NULL,
	[estimated_diameter_meters_min] DOUBLE PRECISION NULL,
	[estimated_diameter_meters_max] DOUBLE PRECISION NULL,
	[estimated_diameter_miles_min] DOUBLE PRECISION NULL,
	[estimated_diameter_miles_max] DOUBLE PRECISION NULL,
	[estimated_diameter_feet_min] DOUBLE PRECISION NULL,
	[estimated_diameter_feet_max] DOUBLE PRECISION NULL,
	[is_potentially_hazardous_asteroid] BOOLEAN NOT NULL,
	[close_approach_date] DATE NULL,
	[close_approach_date_full] TIMESTAMP NULL,
	[epoch_date_close_approach] BIGINT NULL,
	[relative_velocity_kilometers_per_second] DOUBLE PRECISION NULL,
	[relative_velocity_kilometers_per_hour] DOUBLE PRECISION NULL,
	[relative_velocity_miles_per_hour] DOUBLE PRECISION NULL,
	[miss_distance_astronomical] DOUBLE PRECISION NULL,
	[miss_distance_lunar] DOUBLE PRECISION NULL,
	[miss_distance_kilometers] DOUBLE PRECISION NULL,
	[miss_distance_miles] DOUBLE PRECISION NULL,
	[orbiting_body] VARCHAR(50) NULL,
	[is_sentry_object] BOOLEAN NOT null
)
SORTKEY(name);